pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tushnikbiswas/springboot-cicd.git'
            }
        }

        stage('Build with Maven') {
            steps {
                bat 'mvn clean package -f app/pom.xml'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t springboot-tomcat .'
            }
        }

        stage('Deploy Container') {
            steps {
                bat '''
                docker stop springboot-app || true
                docker rm springboot-app || true
                docker run -d -p 8080:8080 --name springboot-app springboot-tomcat
                '''
            }
        }
    }
}
